set nocompatible              " be iMproved, required                                                                                                                                                                
filetype off                  " required                                                                                                                                                                             
                                                                                                                                                                                                                     
" set the runtime path to include Vundle and initialize                                                                                                                                                              
set rtp+=~/.vim/bundle/Vundle.vim                                                                                                                                                                                    
call vundle#begin()                                                                                                                                                                                                  
" alternatively, pass a path where Vundle should install plugins                                                                                                                                                     
"call vundle#begin('~/some/path/here')                                                                                                                                                                               
                                                                                                                                                                                                                     
" let Vundle manage Vundle, required                                                                                                                                                                                 
Plugin 'VundleVim/Vundle.vim'                                                                                                                                                                                        
                                                                                                                                                                                                                     
" The following are examples of different formats supported.                                                                                                                                                         
" Keep Plugin commands between vundle#begin/end.                                                                                                                                                                     
" plugin on GitHub repo                                                                                                                                                                                              
Plugin 'tpope/vim-fugitive'                                                                                                                                                                                          
" plugin from http://vim-scripts.org/vim/scripts.html                                                                                                                                                                
Plugin 'L9'                                                                                                                                                                                                          
" Git plugin not hosted on GitHub                                                                                                                                                                                    
Plugin 'git://git.wincent.com/command-t.git'                                                                                                                                                                         
" The sparkup vim script is in a subdirectory of this repo called vim.                                                                                                                                               
" Pass the path to set the runtimepath properly.                                                                                                                                                                     
Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}                                                                                                                                                                           
" Folders tree                                                                                                                                                                                                       
Plugin 'scrooloose/nerdtree'                                                                                                                                                                                         
" Syntastic                                                                                                                                                                                                          
Plugin 'scrooloose/syntastic'                                                                                                                                                                                        
" Solarized                                                                                                                                                                                                          
Plugin 'altercation/vim-colors-solarized'                                                                                                                                                                            
" Airline                                                                                                                                                                                                            
"Plugin 'bling/vim-airline'                                                                                                                                                                                          
" Powerline                                                                                                                                                                                                          
Plugin 'powerline/powerline'                                                                                                                                                                                         
" NERDCommenter                                                                                                                                                                                                      
Plugin 'scrooloose/nerdcommenter'                                                                                                                                                                                    
" Vdebug                                                                                                                                                                                                             
Plugin 'joonty/vdebug'                                                                                                                                                                                               
" PIV                                                                                                                                                                                                                
Plugin 'spf13/PIV'                                                                                                                                                                                                   
" VIM-addon-mw-utils                                                                                                                                                                                                 
Plugin 'marcweber/vim-addon-mw-utils'                                                                                                                                                                                
" VIM-snipmate                                                                                                                                                                                                       
Plugin 'garbas/vim-snipmate'                                                                                                                                                                                         
" Supertab                                                                                                                                                                                                           
Plugin 'ervandew/supertab'                                                                                                                                                                                           
" DelimitMate                                                                                                                                                                                                        
Plugin 'Raimondi/delimitMate'                                                                                                                                                                                        
" Matchit                                                                                                                                                                                                            
Plugin 'tmhedberg/matchit'                                                                                                                                                                                           
" Checksyntax_vim                                                                                                                                                                                                    
Plugin 'tomtom/checksyntax_vim'                                                                                                                                                                                      
" VIM-surround                                                                                                                                                                                                       
Plugin 'tpope/vim-surround'                                                                                                                                                                                          
" HTML-AutoCloseTag                                                                                                                                                                                                  
Plugin 'vim-scripts/HTML-AutoCloseTag'                                                                                                                                                                               
" Colorizer                                     
Plugin 'lilydjwg/colorizer'                                                                                                                                                                                          
" HTTPlog                                                                                                                                                                                                            
Plugin 'vim-scripts/httplog'                                                                                                                                                                                         
" PHP-cs-fixer'                                                                                                                                                                                                      
Plugin 'stephpy/vim-php-cs-fixer'                                                                                                                                                                                    
" VIM-markdown-preview                                                                                                                                                                                               
Plugin 'JamshedVesuna/vim-markdown-preview'                                                                                                                                                                          
" YouCompleteMe                                                                                                                                                                                                      
Plugin 'Valloric/YouCompleteMe'                                                                                                                                                                                      
" Tabular                                                                                                                                                                                                            
Plugin 'godlygeek/tabular'                                                                                                                                                                                           
" vim-javascript-syntax                                                                                                                                                                                              
Plugin 'jelera/vim-javascript-syntax'                                                                                                                                                                                
" VIMtex                                                                                                                                                                                                             
Plugin 'lervag/vimtex'                                                                                                                                                                                               
                                                                                                                                                                                                                     
" All of your Plugins must be added before the following line                                                                                                                                                        
call vundle#end()            " required                                                                                                                                                                              
filetype plugin indent on    " required                                                                                                                                                                              
" To ignore plugin indent changes, instead use:                                                                                                                                                                      
filetype plugin on                                                                                                                                                                                                   
"                                                                                                                                                                                                                    
" Brief help                                                                                                                                                                                                         
" :PluginList       - lists configured plugins                                                                                                                                                                       
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate                                                                                                                                   
" :PluginSearch foo - searches for foo; append `!` to refresh local cache                                                                                                                                            
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal                                                                                                                         
"                                                                                                                                                                                                                    
" see :h vundle for more details or wiki for FAQ                                                                                                                                                                     
" Put your non-Plugin stuff after this line                                                                                                                                                                          
                                                                                                                                                                                                                     
" vim-javascript-syntax                                                                                                                                                                                              
"au FileType javascript call JavaScriptFold()                                                                                                                                                                        
                                                                                                                                                                                                                     
" NERDTree                                                                                                                                                                                                           
let g:NERDTreeDirArrowExpandable = '▸'                                                                                                                                                                               
let g:NERDTreeDirArrowCollapsible = '▾'                                                                                                                                                                              
                                                                                                                                                                                                                     
" Syntastic recommanded settings                                                                                                                                                                                     
set statusline+=%#warningmsg#                                                                                                                                                                                        
set statusline+=%{SyntasticStatuslineFlag()}                                                                                                                                                                         
set statusline+=%*                                                                                                                                                                                                   
                                                                                                                                                                                                                     
let g:syntastic_always_populate_loc_list = 1                                                                                                                                                                         
let g:syntastic_auto_loc_list = 1                                                                                                                                                                                    
let g:syntastic_check_on_open = 1                                                                                                                                                                                    
let g:syntastic_check_on_wq = 0                                                                                                                                                                                      
                                                                                                                                                                                                                     
" Solarized                                                                                                                                                                                                          
syntax enable                                                                                                                                                                                                        
set background=dark                                                                                                                                                                                                  
colorscheme solarized                                                                                                                                                                                                
                                                                                                                                                                                                                     
" PHP-cs-fixer                                                                                                                                                                                                       
" If php-cs-fixer is in $PATH, you don't need to define line below                                                                                                                                                   
" let g:php_cs_fixer_path = "~/php-cs-fixer.phar" " define the path to the php-cs-fixer.phar
let g:php_cs_fixer_level = "symfony"              " which level ?                                                                                                                                                    
let g:php_cs_fixer_config = "default"             " configuration                                                                                                                                                    
let g:php_cs_fixer_php_path = "php"               " Path to PHP                                                                                                                                                      
" If you want to define specific fixers:                                                                                                                                                                             
" let g:php_cs_fixer_fixers_list = "linefeed,short_tag,indentation"                                                                                                                                                  
let g:php_cs_fixer_enable_default_mapping = 1     " Enable the mapping by default (<leader>pcd)                                                                                                                      
let g:php_cs_fixer_dry_run = 0                    " Call command with dry-run option                                                                                                                                 
let g:php_cs_fixer_verbose = 0                    " Return the output of command if 1, else an inline information.                                                                                                   
                                                                                                                                                                                                                     
" General vim settings                                                                                                                                                                                               
" """"""""""""""""""""""""""""""""""""""""""                                                                                                                                                                         
" solarized toggle background                                                                                                                                                                                        
function! ToggleBackground()                                                                                                                                                                                         
    if (w:solarized_style=="dark")                                                                                                                                                                                   
    let w:solarized_style="light"                                                                                                                                                                                    
    colorscheme solarized                                                                                                                                                                                            
else                                                                                                                                                                                                                 
    let w:solarized_style="dark"                                                                                                                                                                                     
    colorscheme solarized                                                                                                                                                                                            
endif                                                                                                                                                                                                                
endfunction                                                                                                                                                                                                          
command! Togbg call ToggleBackground()                                                                                                                                                                               
nnoremap <leader>b :call ToggleBackground()<CR>                                                                                                                                                                      
inoremap <leader>b <ESC>:call ToggleBackground()<CR>                                                                                                                                                                 
vnoremap <leader>b <ESC>:call ToggleBackground()<CR>                                                                                                                                                                 
                                                                                                                                                                                                                     
set number                                                                                                                                                                                                           
set hlsearch                                                                                                                                                                                                         
set incsearch                                                                                                                                                                                                        
                                                                                                                                                                                                                     
set tabstop=4                                                                                                                                                                                                        
" show existing tab with 4 spaces width                                                                                                                                                                              
set tabstop=4                                                                                                                                                                                                        
" " when indenting with '>', use 4 spaces width                                                                                                                                                                      
set shiftwidth=4                                                                                                                                                                                                     
" " On pressing tab, insert 4 spaces                                                                                                                                                                                 
set expandtab                                                                                                                                                                                                        
" highlight dark                                                                                                                                                                                                     
" """""""""""""""""""""""""""""""""""""""""""
